services:
  fire-simulator:
    build:
      context: ./fire-simulator
      dockerfile: Dockerfile
    container_name: fire-simulator
    restart: unless-stopped
    ports:
      - "127.0.0.1:3200:3000"
